#!/bin/bash

# Load functions from library
. /etc/init.d/functions

# Name of the application
app="pg_tools"

# Start the service
run() {
    echo -n $"Starting $app:"
    $app &

    sleep 1

    status $app > /dev/null
    # If application is running
    if [[ $? -eq 0 ]]; then
        if [ ! -d "/var/run/pg_tools/" ]; then
            mkdir -p /var/run/pg_tools/
        fi

        # Store PID in run file
        echo $! > /var/run/pg_tools/$app.pid
            success
            echo
    else
        failure
        echo
    fi
}

# Start the service
start() {
    status $app > /dev/null
    # If application is running
    if [[ $? -eq 0 ]]; then
        status $app
    else
        run
    fi
}

# Restart the service
stop() {
    echo -n "Stopping $app: "
    killproc $app
    rm -f /var/run/pg_tools/$app
    echo
}

# Reload the service
reload() {
    status $app > /dev/null
    # If application is running
    if [[ $? -eq 0 ]]; then
        echo -n $"Reloading $app:"
        kill -HUP `pidof $app`
        sleep 1
        status $app > /dev/null
        # If application is running
        if [[ $? -eq 0 ]]; then
            success
            echo
        else
            failure
            echo
        fi
    else
        run
    fi
}

# Main logic
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status $app
    ;;
  restart)
    stop
    sleep 1
    start
    ;;
  reload)
    reload
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac

exit $?