# Default values for pgtools
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image:
  repository: placidina/pg-tools
  tag: 2.0.2
  pullPolicy: IfNotPresent
  pullSecrets: []

## Number of desired Pods.
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#replicas
replicaCount: 1

## The update strategy to apply to the Deployment or DaemonSet
## ref https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
deploymentStrategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 100%

## Additional deployment labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
deploymentLabels: {}

## Additional deployment annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
deploymentAnnotations: {}

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

## Additional pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## Toleration labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
tolerations: []
# - key: "key"
#   operator: "Equal|Exists"
#   value: "value"
#   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

## Affinity settings for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
  ## An example of preferred pod anti-affinity, weight is in the range 1-100
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchExpressions:
  #         - key: app
  #           operator: In
  #           values:
  #           - scheduler-default
  #       topologyKey: kubernetes.io/hostname

  ## An example of required pod anti-affinity
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #       - key: app
  #         operator: In
  #         values:
  #         - scheduler-default
  #     topologyKey: "kubernetes.io/hostname"

## Name of Priority Class to assign pods
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
# priorityClassName: ""

## Managing Compute Resources for Containers
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

## Containers, which are run before the app containers are started.
extraInitContainers: []
# - name: init-myservice
#   image: busybox
#   command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']

## Define a Command and Arguments for a Container
## ref: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
commandOverrides: []

## Additional environment variables to set
extraEnvs: []
# - name: NODE_ENV
#   value: production

## Additional volumeMounts to the controller main container
extraVolumeMounts: []  
# - name: ftp-reports-export
#   mountPath: /var/lib/ftp-reports-export

## Additional volumes to the controller pod
extraVolumes: []
# - name: ftp-reports-export
#   emptyDir: {}

## Container lifecycle hooks
## ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
lifecycle: {}
  # postStart:
  #   exec:
  #     command: []
  # preStop:
  #   exec:
  #     command: []

## Readiness probe values
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
readinessProbe: {}
  # exec:
  #   command:
  #   - /bin/sh
  #   - -c
  #   - |
  #     #!/usr/bin/env ash
  #     set -eux
  #     ps -e | grep pgtools
  # failureThreshold: 3
  # initialDelaySeconds: 10
  # periodSeconds: 15
  # successThreshold: 1
  # timeoutSeconds: 15

## Liveness probe values
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
livenessProbe: {}
  # exec:
  #   command:
  #   - /bin/sh
  #   - -c
  #   - |
  #     #!/usr/bin/env ash
  #     set -eux
  #     ps -e | grep pgtools
  # failureThreshold: 3
  # initialDelaySeconds: 10
  # periodSeconds: 15
  # successThreshold: 1
  # timeoutSeconds: 15

## Pod termination grace period
terminationGracePeriodSeconds: 30

# Custom pgtools.conf to override the default ones in the configmap
# config: |
#   database = {
#       host="127.0.0.1";
#       username="postgres";
#       password="123";
#       name="template1";
#   };

#   modules = {
#       cycle = 30;
#       transactions = {
#           idle = {
#               enabled = true;
#               timeout = 60;
#               session = false;
#           };
#       };
#   };

serviceAccount:
  ## Specifies whether a service account should be created
  create: true
  ## Additional annotations for service account
  annotations: {}
  ## The name of the service account to use.
  ## If not set and create is true, a name is generated using the fullname template
  name: